Revert "Use the NDK cpufeatures directly."
This reverts commit 8c2ed69cb2250633188d2e70f7b71d8cf22603b8.

Broke sdk (linux) build in git_mirror-aosp-master-with-vendor:

In file included from external/webp/src/dsp/lossless_neon.c:18:
prebuilts/clang/host/linux-x86/clang-2812033/bin/../lib64/clang/3.8.256229/include/arm_neon.h:28:2: error: "NEON support not enabled"

Change-Id: I7d8db62eec5362d6be34488eff35faad0aac52fa